#!/bin/bash

######## Amazon Linux 2 #######
######## Install httpd (Linux 2 version)
yum update -y
yum install -y httpd.x86_64
systemctl start httpd.service
systemctl enable httpd.service
echo "Hello World from $(hostname -f)" > /var/www/html/index.html



## note: Http user data automatically runs with the sudo user
